name: Update Currency Rates

on:
  schedule:
    # Run every day at 16:00 UTC (after ECB publishes rates)
    - cron: "0 16 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update rates
        run: pnpm run update

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet latest.json latest.min.json || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version
        if: steps.check_changes.outputs.has_changes == 'true'
        id: version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEW_VERSION="1.1.$((PATCH_VERSION + 1))"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          pnpm version ${{ steps.version.outputs.new_version }} --no-git-tag-version

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add latest.json latest.min.json package.json
          git commit -m "chore: update currency rates [skip ci]"
          git tag v${{ steps.version.outputs.new_version }}
          git push
          git push --tags

      - name: Create Release
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          body: |
            Currency rates updated at ${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
